name: Code Linting
run-name: Running Github Actions Linting ğŸš€
on: [push, pull_request]
jobs:
  Run-Python-Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Run all linting
        run: |
          make lint
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  Run-Python-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python Tests
        run: |
          make test
      - run: echo "ğŸ This job's status is ${{ job.status }}."

